"""Reusable execution and evaluation contracts for long-running harness stages."""

from .evaluation import (
    ConvergenceAction,
    CriterionResult,
    CriterionStatus,
    Decision,
    EvaluationResult,
    EvaluatorIntegrity,
    MetricObservation,
    ProgressRecord,
    TaskObjective,
    TraceabilityRecord,
)
from .execution import (
    ArtifactRecord,
    CommandResult,
    ContractViolation,
    InputRecord,
    InputSnapshot,
    OptionalCapabilityUnavailable,
    Provenance,
    StageOutcome,
    StageResult,
    capture_input,
    create_run_root,
    describe_artifact,
    run_external,
    run_optional_stage,
    verify_artifact,
    verify_input,
)

__all__ = [
    "ArtifactRecord",
    "CommandResult",
    "ContractViolation",
    "CriterionResult",
    "CriterionStatus",
    "ConvergenceAction",
    "Decision",
    "EvaluationResult",
    "EvaluatorIntegrity",
    "InputRecord",
    "InputSnapshot",
    "MetricObservation",
    "OptionalCapabilityUnavailable",
    "ProgressRecord",
    "Provenance",
    "StageOutcome",
    "StageResult",
    "TaskObjective",
    "TraceabilityRecord",
    "capture_input",
    "create_run_root",
    "describe_artifact",
    "run_external",
    "run_optional_stage",
    "verify_artifact",
    "verify_input",
]
